name: Build and Deploy

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://r0.fyi
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Install SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add Known Host
        run: |
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VPS
        run: rsync -avz --delete _site/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.SSH_PATH }}

      - name: IndexNow
        run: |
          HTTP_CODE=$(curl -s -o response.txt -w "%{http_code}" -X POST "https://api.indexnow.org/indexnow" \
            -H "Content-Type: application/json" \
            -d @./_site/indexnow.json)

          echo "Body:"
          cat ./_site/indexnow.json
          echo ""

          echo "Response:"
          cat response.txt
          echo ""

          if [[ "$HTTP_CODE" =~ ^2 ]]; then
            echo "Successfully sent IndexNow request (HTTP $HTTP_CODE)"
          else
            echo "IndexNow failed (HTTP $HTTP_CODE)"
            exit 1
          fi
